-- 1. Create CUSTOMER Table and Insert Values Using Sequence S1
CREATE TABLE CUSTOMER(
  C_ID NUMBER,
  C_NAME VARCHAR2(10),
  C_ADDRESS VARCHAR2(10)
);

CREATE SEQUENCE S1;

-- Inserting records into the CUSTOMER table
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'LAVANYA', 'PRABHADEVI');
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'BHAVIKA', 'DADAR');

-- View inserted data
SELECT * FROM CUSTOMER;


-- 2. Alter SEQUENCE S1 to Increment By 2 and Insert Additional Values
ALTER SEQUENCE S1
  INCREMENT BY 2
  CACHE 2;

-- Insert new values after altering the sequence
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'SANIKA', 'KURLA');

-- View all records
SELECT * FROM CUSTOMER;


-- 3. Alter SEQUENCE S1 With MAXVALUE, Cache, and Cycle Settings and Insert Values
ALTER SEQUENCE S1
  MAXVALUE 10
  CACHE 2
  CYCLE;

-- Insert records after altering sequence with cycle
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'LIPA', 'VIDYAVIHAR');
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'LIPA', 'VIDYAVIHAR');
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'LIPA', 'VIDYAVIHAR');
INSERT INTO CUSTOMER VALUES (S1.NEXTVAL, 'LIPA', 'VIDYAVIHAR');

-- View all records
SELECT * FROM CUSTOMER;


-- 4. Create SEQUENCE S2 With No Cycle and Insert Multiple Values
CREATE SEQUENCE S2
  MAXVALUE 4
  CACHE 2
  NOCYCLE;

-- Insert values using sequence S2
INSERT INTO CUSTOMER VALUES (S2.NEXTVAL, 'SANIKA', 'KURLA');
INSERT INTO CUSTOMER VALUES (S2.NEXTVAL, 'SANIKA', 'KURLA');
INSERT INTO CUSTOMER VALUES (S2.NEXTVAL, 'SANIKA', 'KURLA');
INSERT INTO CUSTOMER VALUES (S2.NEXTVAL, 'SANIKA', 'KURLA');
INSERT INTO CUSTOMER VALUES (S2.NEXTVAL, 'SANIKA', 'KURLA');

-- View all records
SELECT * FROM CUSTOMER;

--5. Drop the sequence S2 (Q4) after use
DROP SEQUENCE S2;
